apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-content
data:
  index.html: |
    <html>
        <h1>Welcome to APP 3</h1>
    </html>
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: app3-content
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service3
spec:
  type: ClusterIP
  selector:
    app: app3
  ports:
    - port: 80
      targetPort: 80